[project]
name = "about"
version = "0.1.0"
description = "About Joel E Carlson"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf>=1.7.2",
    "markdown>=3.10.1",
    "ruff>=0.14.14",
]

